#!/bin/sh
# Compile some Emacs LISP files.
# Copyright © 1995 Progiciels Bourbeau-Pinard inc.
# François Pinard <pinard@iro.umontreal.ca>, 1995.

setpath=/tmp/elc.$$

echo "(setq load-path (cons nil load-path))" > $setpath
if emacs -batch -l $setpath -f batch-byte-compile $*; then
  rm -f $setpath
else
  rm -f $setpath
  exit 1
fi
