#!/usr/bin/env python
# Copyright © 2001 Progiciels Bourbeau-Pinard inc.
# François Pinard <pinard@iro.umontreal.ca>, 2001.

"""\
Interface between Emacs LISP and Python - Python process starter.

One of the goals of this small bootstrap is so `pymacs.py' can be kept
in compiled form.
"""

pymacsdir = '@pymacsdir@'

if __name__ == '__main__':
    import pymacs, sys
    if pymacsdir:
        apply(pymacs.main, [pymacsdir] + sys.argv[1:])
    else:
        apply(pymacs.main, sys.argv[1:])
