#!/usr/bin/env python
# -*- coding: Latin-1 -*-
# Copyright © 2002, 2003 Progiciels Bourbeau-Pinard inc.
# François Pinard <pinard@iro.umontreal.ca>, 2002.

"""\
Handling of boxed comments in various box styles.
"""

import sys
from Pymacs.Rebox import rebox
apply(rebox.main, tuple(sys.argv[1:]))
